### ISSUE TITLE
Fix collision problems

### ISSUE THREAD

**Issue by CypherConjured** [CypherConjured/StaticCurrent#3]
During gameplay, the Player is able to stick into platforms by moving towards the side of the platform and jumping into it. Further refinement may be needed on the collision detection algorithm.

Steps to Reproduce:
1.) Launch the game.
2.) Progress into the playable part of the game.
3.) Attempt to jump into the side of the platform,
4.) Observe, the Player will stick into the side of the platform until moving or jumping away.

**Comment by WillNiels128** [comment]
Note, this issue is easily reproduced on slopes.

**Comment by CypherConjured** [comment]
I may have fixed this...
